name = "matthew"
type = "webpack"
account_id = "e009db83777a491f852bb4f2d7e154da"
workers_dev = true
route = "*beardsley.com.au/*"
zone_id = "dfb1b7e21ac4f9ddcb1cfa785a4b0d9f"

[site]
bucket = "./public"
entry-point = "workers-site"
